sudo: false
language: perl
perl:
    - "5.8"
    - "5.10"
    - "5.22"
    - "5.24"
install:
    - cpanm -n -q --with-recommends --installdeps .
script:
    - perl Build.PL && ./Build build && ./Build test
